### ISSUE TITLE
vercel project fails to build

### ISSUE THREAD

**Issue by dpi0** [chroxify/haptic#12]
On using the one-click deploy instance [link](https://vercel.com/new/clone?repository-url=https://github.com/chroxify/haptic&project-name=haptic-web&repository-name=haptic-web&path=apps/desktop) on the README.md, the vercel project fails to build.

Here is the deployment log from vercel: https://spaceb.in/KizMkREX

Here are some screenshots:

![A_(20-16-04)_(05-Sep)](https://github.com/user-attachments/assets/d4292401-785e-45c8-a605-f43901341c9e)

![A_(20-17-32)_(05-Sep)](https://github.com/user-attachments/assets/4670b952-d78c-4cb4-bf60-a32512ed8051)

**Comment by scifisatan** [comment]
same error, maybe its not a one click deploy after all. 
i guess it can be solved by forking the repo and changing the deploy settings.

**Comment by chroxify** [comment]
Thanks for opening an issue, and sorry for the trouble! This was actually a mistake on my end, as the wrong query parameter was set in the clone URL

To fix this, please open the project, go to `Settings > General`, and under `Root Directory`, enter `apps/web`.

The deploy button should work correctly from now on though!

**Comment by dpi0** [comment]
> To fix this, please open the project, go to `Settings > General`, and under `Root Directory`, enter `apps/web`.

Although the deployment works now, shouldn't this be a "one-click" deployment without any need of a manual setting change? If not, the README should contain the instructions for this setting change.

BTW: loving the app so far! 👏🏽 excellent job on the responsiveness and the UI. self hosting using docker

**Comment by chroxify** [comment]
Thank you! And yes, I updated the README yesterday, you might have missed that. Meaning now there won't be any extra setting changes necessary

**Comment by dpi0** [comment]
Yup it's fixed! Sorry was in a hurry didn't look at the commit history. Closing this issue now.
